<?php

return [
    'DASHBOARD' => 1,
    'HR' => 2,
    'EMPLOYEES' => 3,
    'DMS' => 4,
    'DRIVERTYPES' => 5,
    'DRIVERS' => 6,
    'DRIVERDIFFERENCE' => 20,
    'OPERATIONSUPERVISERDIFFERENCE' => 25,
    'ADDRECEIPT' => 22, // FOR create receipt
    'RECEIPTlOG' => 23,
    'DRIVERDIFFERENCELOG' => 24,
    'OPERATIONSUPERVISERDIFFERENCELOG' => 26,
    'BOOKLET' => 21,
    'BUSINESSES' => 7,
    // 'BUSINESSESID' => 8,
    'COORDINATORREPORT' => 8,
    'PLATFORMIDSREPORT' => 16,
    'LOGS' => 17,
    'PENALTY' => 18,
    'PAYROLL' => 9,
    'REVENUEREPORTING' => 10,
    'BUSINESSFIELDS' => 11,
    'ROLE' => 12,
    'VIEW' => 'is_view',
    'ADD' => 'is_add',
    'EDIT' => 'is_edit',
    'DELETE' => 'is_delete',
];
